name: Deploy Vite Vue App to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Updated to v4

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci  # Clean install (faster & more reliable)

      - name: Build
        run: npm run build

      - name: Verify build output
        run: ls -R dist  # Ensure 'dist' exists

      - name: Configure Pages
        uses: actions/configure-pages@v4  # Updated to v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2  # Correct for Pages
        with:
          path: dist  # Vite's default output

      - name: Deploy
        uses: actions/deploy-pages@v2  # Updated to v2
